### ISSUE TITLE
Impossible de modifier la date d'une opération : "internal server error"

### ISSUE THREAD

**Issue by fazuuuu** [suntorvic/malte2#59]
Le problème est limité à cette opération spécifique. Toutes les autres opérations peuvent être modifiées.

![Capture d’écran 2022-11-15 083159](https://user-images.githubusercontent.com/63877657/201857048-7d65462c-f2ed-4008-bde8-551715ba0070.png)
![Capture d’écran 2022-11-15 083215](https://user-images.githubusercontent.com/63877657/201857059-94a9255b-b278-4c4d-8448-3e3a7050e959.png)

**Comment by fazuuuu** [comment]
But de la modif : passer la date du 15 au 14

**Comment by flmmkch** [comment]
Tu peux ouvrir la console de développeur dans l'onglet Réseau (ctrl+shift+e sous Firefox), refaire "Valider" et envoyer la capture d'écran avec la réponse ?
Et aussi une copie du contenu du terminal dans la fenêtre Windows ouverte par l'application, il y a des détails sur l'erreur

**Comment by fazuuuu** [comment]
![Capture d’écran 2022-11-15 101701](https://user-images.githubusercontent.com/63877657/201880171-58549886-40d3-49d2-918d-55596b2a2195.png)
![Capture d’écran 2022-11-15 101832](https://user-images.githubusercontent.com/63877657/201880175-dcceb89e-a18c-463d-9b4c-29884ed8f3b8.png)

**Comment by flmmkch** [comment]
Ha mais ici la catégorie est nulle... donc il ne devrait pas y avoir d'erreur c'est curieux

**Comment by flmmkch** [comment]
OK je reproduis le problème il faut :

1. créer une opération 1 avec une imputation comptable A et une catégorie liée à cette opération comptable
2. créer une opération 2 et changer l'imputation comptable B, valider
3. modifier l'opération 2 et valider

À l'étape 2, l'opération a été entrée avec l'imputation B mais avec la catégorie de l'imputation A.
