### ISSUE TITLE
Impossible d'ajouter une nouvelle opération en 2023

### ISSUE THREAD

**Issue by fazuuuu** [suntorvic/malte2#70]
Lors de l'appui sur la touche "Enregistrer" après avoir rentré les détails d'une nouvelle opération, rien ne se passe. (Depuis le 01/01/23 uniquement).

**Comment by fazuuuu** [comment]
De plus, le mois de janvier 2023 affiche l'intégralité des opérations de 2022.
![image](https://user-images.githubusercontent.com/63877657/210182143-c05c82ec-67ad-4bc8-a25a-cdebfc691851.png)

**Comment by flmmkch** [comment]
A valider de votre côté, chez moi les opérations s'enregistrent bien après la correction en tous cas :thinking:

**Comment by flmmkch** [comment]
Je pense que les opérations que tu as enregistré ont été placées en janvier 2022...
