### ISSUE TITLE
Les repas enregistrés entre le 13 et le 31 janvier 2022 apparaissent à la même date en 2023

### ISSUE THREAD

**Issue by fazuuuu** [suntorvic/malte2#71]
![image](https://user-images.githubusercontent.com/63877657/210182053-5d56fa9f-52a8-4b81-b4c7-83aee5eef039.png)
![image](https://user-images.githubusercontent.com/63877657/210182063-d0f7c3f3-113a-4dae-911b-74b5e969a072.png)

**Comment by fazuuuu** [comment]
Mais pas tous... Ainsi du 13 janvier 2023 au 31 janvier 2023 les repas sont indiques à ceux de 2022 sur la même période. 
Du 1 au 12 janvier 2023, des repas ont été indiqué, mais je ne saurais pas dire pourquoi. 
Les mois qui suivent janvier 2023 n'ont rien d'indiqué (voir images ci après).

![image](https://user-images.githubusercontent.com/63877657/210182242-d38b07c3-01c2-447c-8351-552a760ccf7d.png)
![image](https://user-images.githubusercontent.com/63877657/210182248-6338d79c-e214-4cb0-b1e4-d7c194004f4a.png)

**Comment by fazuuuu** [comment]
Il se pourrait que ces entrées ne soient pas dues à un bug mais à une erreur d'entrée des opérateurs.

**Comment by flmmkch** [comment]
Tu pourras ré-ouvrir ce ticket si le bug n'est pas complètement corrigé
